--- 
  env:
    variables:
      BROWSER: "chrome"
  phases: 

    build: 
      commands: 
        - "echo Build started on `date`"
        - "echo Compiling the Node.js code"
        - "npm run test_ci"
    install: 
      commands: 
        - "echo Installing Dependancies..."
        - "npm install"
      runtime-versions: 
        nodejs: 12
    pre_build: 
      commands: 
        - "echo Installing source NPM dependencies..."
        - "sudo npx playwright install-deps"
  version: 0.2
